In [186]:
import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
import  seaborn as sns

In [187]:
df = pd.read_csv("Telco-Customer-Churn.csv")

In [188]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [58]:
df.info() # The column 'TotalCharges' is supposed to be numerical but showing string

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [60]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')  # Convert the TotalCharges column to numerical value

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [62]:
df.dropna(how='any', inplace=True) # Dropping the 11 missing rows fron the TotalCharges on all the columns for uniformity.
                                   # Please note: The missing value could be imputed using mmean, mode etc

In [63]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.9 MB

In [64]:
len(df)

7032

In [66]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [68]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [69]:
# Getting my independent variable, in this case the X variable
X=df.drop(['customerID', 'Churn'], axis=1)

In [71]:
# Getting the dependent variable, in this case the y-variable
y = df['Churn']

In [189]:
y = y.map({'Yes':1, 'No':0})  # Converting the categorical values to numerical values

In [72]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [190]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [74]:
# Convert categorical features to numericals using Feature Encoding and Dummy Encoding
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [148]:
X.head(3)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1

In [191]:
X.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   gender_Male                            7032 non-null   int64
 5   Partner_Yes                            7032 non-null   int64
 6   Dependents_Yes                         7032 non-null   int64
 7   PhoneService_Yes                       7032 non-null   int64
 8   MultipleLines_No phone service         7032 non-null   int64
 9   MultipleLines_Yes                      7032 non-null   int64
 10  InternetService_Fiber optic            7032 non-null   int64
 11  InternetService_No                     7032 non-null   int64
 12  OnlineSecurity_No internet service     7032 non-null   int64
 13  OnlineSecurity_Yes                     7032 non-null   int64
 14  OnlineBackup_No internet service       7032 non-null   int64
 15  OnlineBackup_Yes                       7032 non-null   int64
 16  DeviceProtection_No internet service   7032 non-null   int64
 17  DeviceProtection_Yes                   7032 non-null   int64
 18  TechSupport_No internet service        7032 non-null   int64
 19  TechSupport_Yes                        7032 non-null   int64
 20  StreamingTV_No internet service        7032 non-null   int64
 21  StreamingTV_Yes                        7032 non-null   int64
 22  StreamingMovies_No internet service    7032 non-null   int64
 23  StreamingMovies_Yes                    7032 non-null   int64
 24  Contract_One year                      7032 non-null   int64
 25  Contract_Two year                      7032 non-null   int64
 26  PaperlessBilling_Yes                   7032 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7032 non-null   int64
 28  PaymentMethod_Electronic check         7032 non-null   int64
 29  PaymentMethod_Mailed check             7032 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 1.7 MB

In [149]:
# Splitting the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [192]:
X_train.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='str')

In [193]:
len(X_train), len(X_test)

(5274, 1758)

In [194]:
len(y_train), len(y_test)

(5274, 1758)

In [195]:
# Feature Scaling to ensure all the values are in range not too far from each other
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [196]:
X_train_sc

array([[-0.4377158 , -0.74817539, -0.52638   , ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.05601627,  0.85826225, ...,  1.88322907,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  0.59542761,  1.41543565, ..., -0.53100285,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 , -0.9517516 ,  0.54651046, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 ,  0.71757334, -1.48982568, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [ 2.28458741, -0.50388393,  0.29777233, ..., -0.53100285,
         1.39453348, -0.54360352]], shape=(5274, 30))

In [197]:
X_test_sc

array([[ 2.28458741,  1.165441  , -1.31570899, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.54459918, -1.32565851, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.78889063,  1.24629372, ...,  1.88322907,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 ,  0.92114955,  1.06388576, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 , -1.23675829, -0.67064811, ..., -0.53100285,
         1.39453348, -0.54360352],
       [ 2.28458741,  1.04329527,  0.83504669, ..., -0.53100285,
        -0.71708569, -0.54360352]], shape=(1758, 30))

kNN Classifier

In [198]:
# Calling the kNN Classifier
from sklearn.neighbors import KNeighborsClassifier

#initiating the Classifier
model = KNeighborsClassifier()

# Passing the data to the Classifier
model.fit(X_train_sc, y_train)

KNeighborsClassifier()

In [199]:
y_pred = model.predict(X_test_sc)

In [200]:
y_pred

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(1758,), dtype=object)

In [201]:
y_test.head()

2481     No
6784     No
6125    Yes
3052     No
4099     No
Name: Churn, dtype: str

In [202]:
# Classification metrics to check how well the model is performing
from sklearn.metrics import accuracy_score

print(accuracy_score(y_pred, y_test)*100)

75.36973833902162

New Data Prediction

In [203]:
# Creating a new data point to predict if the customer will churn or not

data = pd.DataFrame([[0, 7, 90, 190, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1]], columns=X_train.columns)

In [204]:
data_sc = sc.transform(data)

single_pred = model.predict(data_sc)

In [205]:
print(single_pred)

['No']

In [206]:
data_sc = sc.transform(data)

single_pred = model.predict_proba(data_sc)

In [207]:
single_pred

array([[1., 0.]])

Decision Tree Classifier

In [208]:
# Calling the Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the Classifier
model_dt = DecisionTreeClassifier()

# Passing the data to the Classifier
model_dt.fit(X_train_sc, y_train)

DecisionTreeClassifier()

In [209]:
# Using the X_test data to predict and compare the outcome to the y_test values
y_pred_dt = model_dt.predict(X_test_sc)

In [210]:
y_pred_dt, y_test.values

(array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
       shape=(1758,), dtype=object),
 <ArrowStringArray>
 [ 'No',  'No', 'Yes',  'No',  'No',  'No',  'No',  'No',  'No',  'No',
  ...
   'No', 'Yes',  'No',  'No',  'No',  'No',  'No', 'Yes',  'No',  'No']
 Length: 1758, dtype: str)

In [211]:
# Classification metrics of the decision tree performance
print(accuracy_score(y_test, y_pred_dt)*100)

71.7292377701934

Random Forest Classifier

In [212]:
# Using the random forest classifier
from sklearn.ensemble import  RandomForestClassifier

# Initiating the Classifier
model_rf = RandomForestClassifier(n_estimators=200)

# Passing the training data to the model
model_rf.fit(X_train_sc, y_train)

RandomForestClassifier(n_estimators=200)

In [213]:
# Predictions
y_pred_rf = model_rf.predict(X_test_sc)

In [214]:
y_pred_rf

array(['No', 'No', 'Yes', ..., 'No', 'No', 'No'],
      shape=(1758,), dtype=object)

In [215]:
# Classification metrics for the random forest model
print(accuracy_score(y_pred_rf, y_test)*100)

78.38452787258248

In [120]:
# Other metrics such as recall, precision etc
from sklearn.metrics import recall_score, precision_score, classification_report, roc_auc_score

knn_report = classification_report(y_test, y_pred)
dt_report = classification_report(y_test, y_pred_dt)
rf_report = classification_report(y_test, y_pred_rf)

In [216]:
print('knn report:')
print(knn_report)

knn report:
              precision    recall  f1-score   support

          No       0.83      0.84      0.84      1300
         Yes       0.53      0.50      0.51       458

    accuracy                           0.75      1758
   macro avg       0.68      0.67      0.67      1758
weighted avg       0.75      0.75      0.75      1758

In [217]:
print('dt report:')
print(dt_report)

dt report:
              precision    recall  f1-score   support

          No       0.81      0.81      0.81      1300
         Yes       0.47      0.48      0.47       458

    accuracy                           0.72      1758
   macro avg       0.64      0.64      0.64      1758
weighted avg       0.72      0.72      0.72      1758

In [218]:
print('rf report:')
print(rf_report)

rf report:
              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1300
         Yes       0.62      0.48      0.54       458

    accuracy                           0.79      1758
   macro avg       0.72      0.69      0.70      1758
weighted avg       0.77      0.79      0.78      1758

Naive Bayes Classifier

In [219]:
# Using the Naive Bayes classifier
from sklearn.naive_bayes import  BernoulliNB

# Initiating the Classifier
model_nb = BernoulliNB()

# Passing the training data to the model
model_nb.fit(X_train_sc, y_train)

# Predictions
y_pred_nb = model_nb.predict(X_test_sc)

# Accuracy score of the Naive Bayes model
print(accuracy_score(y_pred_nb, y_test)*100)

71.84300341296928

Support Vector Machine Classifier

In [220]:
# Using the Support Vector Machine classifier
from sklearn.svm import SVC

# Using the Support Vector Machine classifier
model_svm = SVC()

# Passing the training data to the model
model_svm.fit(X_train_sc, y_train)

# Predictions
y_pred_svm = model_svm.predict(X_test_sc)

# Accuracy score of the Support Vector Machine model
print(accuracy_score(y_pred_svm, y_test)*100)

79.29465301478953

In [221]:
svc_report = classification_report(y_test, y_pred_svm)
print('svc report:')
print(svc_report)

svc report:
              precision    recall  f1-score   support

          No       0.83      0.90      0.87      1300
         Yes       0.64      0.48      0.55       458

    accuracy                           0.79      1758
   macro avg       0.73      0.69      0.71      1758
weighted avg       0.78      0.79      0.78      1758

Logistic Regression Classifier

In [222]:
# Using the Logistic Regression classifier
from sklearn.linear_model import LogisticRegression

# Using the Support Vector Machine classifier
model_lr = LogisticRegression()

# Passing the training data to the model
model_lr.fit(X_train_sc, y_train)

# Predictions
y_pred_lr = model_lr.predict(X_test_sc)

# Accuracy score of the Logistic Regression model
print(accuracy_score(y_pred_lr, y_test)*100)

79.01023890784982

In [223]:
lr_report = classification_report(y_test, y_pred_lr)
print('lr report:')
print(lr_report)

lr report:
              precision    recall  f1-score   support

          No       0.84      0.89      0.86      1300
         Yes       0.62      0.52      0.56       458

    accuracy                           0.79      1758
   macro avg       0.73      0.70      0.71      1758
weighted avg       0.78      0.79      0.78      1758