In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

In [62]:
df = pd.read_csv('data.csv')

In [63]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [65]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.dropna(how='any', inplace=True)

In [66]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.9 MB

In [84]:
X=df.drop(['customerID', 'Churn'], axis=1)
y=df.Churn.values

In [85]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [86]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [87]:
y

<ArrowStringArray>
[ 'No',  'No', 'Yes',  'No', 'Yes', 'Yes',  'No',  'No', 'Yes',  'No',
 ...
  'No', 'Yes',  'No',  'No',  'No',  'No',  'No',  'No', 'Yes',  'No']
Length: 7032, dtype: str

In [88]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [89]:
X.head(2)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1

In [93]:
X = np.array(X)

In [94]:
y = np.array(y)

In [105]:
X

array([[  0.  ,   1.  ,  29.85, ...,   0.  ,   1.  ,   0.  ],
       [  0.  ,  34.  ,  56.95, ...,   0.  ,   0.  ,   1.  ],
       [  0.  ,   2.  ,  53.85, ...,   0.  ,   0.  ,   1.  ],
       ...,
       [  0.  ,  11.  ,  29.6 , ...,   0.  ,   1.  ,   0.  ],
       [  1.  ,   4.  ,  74.4 , ...,   0.  ,   0.  ,   1.  ],
       [  0.  ,  66.  , 105.65, ...,   0.  ,   0.  ,   0.  ]],
      shape=(7032, 30))

In [106]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(7032,), dtype=object)

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42,)

In [109]:
# Feature Scaling to standardize the data to ensure all the values are in range not too far from each other
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [110]:
X_train_sc

array([[-0.4377158 , -0.74817539, -0.52638   , ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.05601627,  0.85826225, ...,  1.88322907,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  0.59542761,  1.41543565, ..., -0.53100285,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 , -0.9517516 ,  0.54651046, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 ,  0.71757334, -1.48982568, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [ 2.28458741, -0.50388393,  0.29777233, ..., -0.53100285,
         1.39453348, -0.54360352]], shape=(5274, 30))

In [112]:
X_test_sc

array([[ 2.28458741,  1.165441  , -1.31570899, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.54459918, -1.32565851, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.78889063,  1.24629372, ...,  1.88322907,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 ,  0.92114955,  1.06388576, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 , -1.23675829, -0.67064811, ..., -0.53100285,
         1.39453348, -0.54360352],
       [ 2.28458741,  1.04329527,  0.83504669, ..., -0.53100285,
        -0.71708569, -0.54360352]], shape=(1758, 30))

In [113]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

y_pred_dt = model_dt.predict(X_test_sc)

print(accuracy_score(y_test,y_pred_dt)*100)

71.7292377701934

In [114]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

          No       0.82      0.80      0.81      1300
         Yes       0.46      0.50      0.48       458

    accuracy                           0.72      1758
   macro avg       0.64      0.65      0.64      1758
weighted avg       0.72      0.72      0.72      1758

In [117]:
from imblearn.over_sampling import RandomOverSampler

# Upsample the minority class using RandomOverSampler
oversampler = RandomOverSampler()
X_train_upsampled, y_train_upsampled = oversampler.fit_resample(X_train_sc, y_train)

# Model Building
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train_upsampled, y_train_upsampled)

# Predict on the test set
y_pred_dt2 = model_dt2.predict(X_test_sc)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_dt2) * 100
print("Accuracy:", accuracy)

Accuracy: 72.07053469852104

In [118]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_dt2))

              precision    recall  f1-score   support

          No       0.82      0.80      0.81      1300
         Yes       0.47      0.50      0.48       458

    accuracy                           0.72      1758
   macro avg       0.64      0.65      0.65      1758
weighted avg       0.73      0.72      0.72      1758

In [120]:
y_train_upsampled

array(['No', 'No', 'Yes', ..., 'Yes', 'Yes', 'Yes'],
      shape=(7726,), dtype=object)

In [123]:
from imblearn.under_sampling import RandomUnderSampler

# Downsample the majority class using RandomUnderSampler
downsampler = RandomUnderSampler()
X_train_downsampled, y_train_downsampled = downsampler.fit_resample(X_train_sc, y_train)

# Model Building
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_downsampled, y_train_downsampled)

# Predict on the test set
y_pred_dt3 = model_dt3.predict(X_test_sc)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_dt3) * 100
print("Accuracy:", accuracy)

Accuracy: 67.46302616609783

In [124]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_dt3))

              precision    recall  f1-score   support

          No       0.85      0.67      0.75      1300
         Yes       0.42      0.67      0.52       458

    accuracy                           0.67      1758
   macro avg       0.64      0.67      0.64      1758
weighted avg       0.74      0.67      0.69      1758

In [126]:
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
#SMOTEENN: SMOTE + ENN: Synthetic Minority Over Sampling Technique + Edited Nearest Neighbors
from sklearn.metrics import accuracy_score, classification_report

# Create a SMOTEENN object
smote_enn = SMOTEENN(random_state=42)

# Resample the data
X_train_resampled, y_train_resampled = smote_enn.fit_resample(X_train_sc, y_train)

# Model Building
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt3 = model_dt3.predict(X_test_sc)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_dt3) * 100
print("Accuracy:", accuracy)

Accuracy: 70.64846416382252

In [127]:
# Print classification report
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

          No       0.89      0.69      0.78      1300
         Yes       0.46      0.75      0.57       458

    accuracy                           0.71      1758
   macro avg       0.67      0.72      0.67      1758
weighted avg       0.78      0.71      0.72      1758

In [128]:
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import SMOTE
#SMOTE: Synthetic Minority Over Sampling Technique
from sklearn.metrics import accuracy_score, classification_report

# Create a SMOTE object
smote = SMOTE(random_state=42)

# Resample the data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_sc, y_train)

# Model Building
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt3 = model_dt3.predict(X_test_sc)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_dt3) * 100
print("Accuracy:", accuracy)

Accuracy: 71.78612059158134

In [129]:
# Print classification report
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

          No       0.82      0.79      0.80      1300
         Yes       0.46      0.52      0.49       458

    accuracy                           0.72      1758
   macro avg       0.64      0.65      0.65      1758
weighted avg       0.73      0.72      0.72      1758

In [130]:
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import ADASYN
#ADASYN: Adaptive Synthetic Sampling Approach for Imbalanced Learning
from sklearn.metrics import accuracy_score, classification_report

# Create an ADASYN object
adasyn = ADASYN(random_state=42)

# Resample the data
X_train_resampled, y_train_resampled = adasyn.fit_resample(X_train_sc, y_train)

# Model Building
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt3 = model_dt3.predict(X_test_sc)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_dt3) * 100
print("Accuracy:", accuracy)

Accuracy: 71.27417519908987

In [131]:
# Print classification report
print(classification_report(y_test, y_pred_dt3))

              precision    recall  f1-score   support

          No       0.82      0.78      0.80      1300
         Yes       0.46      0.53      0.49       458

    accuracy                           0.71      1758
   macro avg       0.64      0.65      0.64      1758
weighted avg       0.73      0.71      0.72      1758

In [132]:
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import AllKNN
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [133]:
# Assume 'df' is your dataframe containing the dataset

# Separate features and target variable
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

In [134]:
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [135]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

In [136]:
# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [138]:
# Use AllKNN for undersampling
allknn = AllKNN(sampling_strategy='auto')
X_train_resampled, y_train_resampled = allknn.fit_resample(X_train, y_train)

In [139]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

In [140]:
# Create a decision tree classifier with appropriate parameters
print("Training decision tree...")
dtc = DecisionTreeClassifier(random_state=42, max_depth=5)  # Adjust parameters as needed
dtc.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc.predict(X_test_scaled)

Training decision tree...

In [142]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")

Accuracy of decision tree: 73.54948805460751 %

In [143]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.91      0.71      0.80      1291
         Yes       0.50      0.81      0.62       467

    accuracy                           0.74      1758
   macro avg       0.71      0.76      0.71      1758
weighted avg       0.80      0.74      0.75      1758

In [145]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from imblearn.under_sampling import TomekLinks
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [146]:
# Assume 'df' is your dataframe containing the dataset

# Separate features and target variable
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

In [147]:
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [148]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [149]:
# Use TomekLinks for undersampling
tomek_links = TomekLinks(sampling_strategy='majority')  # not majority gives better results
X_train_resampled, y_train_resampled = tomek_links.fit_resample(X_train, y_train)

In [150]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

In [151]:
# Create a decision tree classifier
dtc = DecisionTreeClassifier(random_state=42)

In [152]:
# Define the parameter grid for fine-tuning
param_grid = {
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [153]:
# Use GridSearchCV for fine-tuning
grid_search = GridSearchCV(dtc, param_grid, cv=5, scoring='accuracy', n_jobs=1)
grid_search.fit(X_train_scaled, y_train_resampled)

# Get the best parameters from the grid search
best_params = grid_search.best_params_

In [154]:
# Print the best parameters
print("Best Parameters:", best_params)

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}

In [155]:
# Create a decision tree classifier with the best parameters
dtc_best = DecisionTreeClassifier(random_state=42, **best_params)
dtc_best.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc_best.predict(X_test_scaled)

In [156]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")

Accuracy of decision tree: 78.32764505119454 %

In [157]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.86      0.85      0.85      1291
         Yes       0.59      0.61      0.60       467

    accuracy                           0.78      1758
   macro avg       0.72      0.73      0.72      1758
weighted avg       0.79      0.78      0.78      1758

In [158]:
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTETomek
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [163]:
# Assume 'df' is your dataframe containing the dataset

# Separate features and target variable
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [164]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [166]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: str

In [167]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [168]:
# Use SMOTETomek for both over-sampling and under-sampling
smote_tomek = SMOTETomek(sampling_strategy=0.5, random_state=42)
X_train_resampled, y_train_resampled = smote_tomek.fit_resample(X_train, y_train)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# Create a decision tree classifier with appropriate parameters
print("Training decision tree...")
dtc = DecisionTreeClassifier(random_state=42, max_depth=5)  # Adjust parameters as needed
dtc.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc.predict(X_test_scaled)

Training decision tree...

In [169]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")

Accuracy of decision tree: 77.7019340159272 %

In [170]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.84      0.86      0.85      1291
         Yes       0.58      0.56      0.57       467

    accuracy                           0.78      1758
   macro avg       0.71      0.71      0.71      1758
weighted avg       0.77      0.78      0.78      1758