In [314]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

In [315]:
# Importing the dataset
df = pd.read_csv('data\\data.csv')

In [316]:
df.head() # Displaying the first 5 rows of the dataset

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [317]:
df.info() # Checking the data types of the columns in the dataset

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [318]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors='coerce') # Converting the TotalCharges column to numeric data type

In [319]:
df.info() # Checking the data types of the columns in the dataset after converting TotalCharges to numeric

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [320]:
# Checking for missing values in the dataset
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [321]:
df.dropna(how='any', inplace=True) # Dropping the rows with missing values

In [322]:
df.isnull().sum() # Checking for missing values in the dataset after dropping rows with missing values

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [323]:
# Dividing the dataset into independent and dependent variables
X=df.drop(['customerID', 'Churn'], axis=1)
y=df['Churn']

In [324]:
X.head(3) # Displaying the first 3 rows of the independent variables

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15

In [325]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [326]:
len(X), len(y) # Checking the length of the independent and dependent variables

(7032, 7032)

In [327]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [328]:
X.head(2)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1

In [329]:
# converting the data type of the independent variable to pandas dataframe
X = pd.DataFrame(X)

In [330]:
X.head(3)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1

In [331]:
# Converting the dependent variable to numerical values
y = pd.DataFrame(y)

In [332]:
y.head(3)

  Churn
0    No
1    No
2   Yes

In [333]:
# Splitting the data into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42,)

In [334]:
X_train.head(3) # Displaying the first 3 rows of the training set

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
3166,0,14,48.80,664.40,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4333,0,31,90.55,2929.75,1,1,0,1,0,1,...,0,0,0,0,0,0,1,1,0,0
1927,0,47,107.35,5118.95,1,1,1,1,0,1,...,0,1,0,1,0,0,1,0,0,0

In [335]:
len(X_train), len(X_test) # Checking the length of the training and testing set

(5274, 1758)

In [336]:
y_train.head(3) # Displaying the first 3 rows of the dependent variable

     Churn
3166    No
4333    No
1927   Yes

In [337]:
len(y_train), len(y_test) # Checking the length of the training and testing set for the dependent variable

(5274, 1758)

In [338]:
X_train.info() # Checking the data types of the columns in the training set

<class 'pandas.DataFrame'>
Index: 5274 entries, 3166 to 862
Data columns (total 30 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          5274 non-null   int64
 1   tenure                                 5274 non-null   int64
 2   MonthlyCharges                         5274 non-null   float64
 3   TotalCharges                           5274 non-null   float64
 4   gender_Male                            5274 non-null   int64
 5   Partner_Yes                            5274 non-null   int64
 6   Dependents_Yes                         5274 non-null   int64
 7   PhoneService_Yes                       5274 non-null   int64
 8   MultipleLines_No phone service         5274 non-null   int64
 9   MultipleLines_Yes                      5274 non-null   int64
 10  InternetService_Fiber optic            5274 non-null   int64
 11  InternetService_No                     5274 non-null   int64
 12  OnlineSecurity_No internet service     5274 non-null   int64
 13  OnlineSecurity_Yes                     5274 non-null   int64
 14  OnlineBackup_No internet service       5274 non-null   int64
 15  OnlineBackup_Yes                       5274 non-null   int64
 16  DeviceProtection_No internet service   5274 non-null   int64
 17  DeviceProtection_Yes                   5274 non-null   int64
 18  TechSupport_No internet service        5274 non-null   int64
 19  TechSupport_Yes                        5274 non-null   int64
 20  StreamingTV_No internet service        5274 non-null   int64
 21  StreamingTV_Yes                        5274 non-null   int64
 22  StreamingMovies_No internet service    5274 non-null   int64
 23  StreamingMovies_Yes                    5274 non-null   int64
 24  Contract_One year                      5274 non-null   int64
 25  Contract_Two year                      5274 non-null   int64
 26  PaperlessBilling_Yes                   5274 non-null   int64
 27  PaymentMethod_Credit card (automatic)  5274 non-null   int64
 28  PaymentMethod_Electronic check         5274 non-null   int64
 29  PaymentMethod_Mailed check             5274 non-null   int64
dtypes: float64(2), int64(28)
memory usage: 1.2 MB

In [339]:
# Standardizing the data using StandardScaler to standardize numerical features so that each feature has a mean of 0 and a standard deviation of 1
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [340]:
X_train_sc

array([[-0.4377158 , -0.74817539, -0.52638   , ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.05601627,  0.85826225, ...,  1.88322907,
        -0.71708569, -0.54360352],
       [-0.4377158 ,  0.59542761,  1.41543565, ..., -0.53100285,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 , -0.9517516 ,  0.54651046, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 ,  0.71757334, -1.48982568, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [ 2.28458741, -0.50388393,  0.29777233, ..., -0.53100285,
         1.39453348, -0.54360352]], shape=(5274, 30))

In [341]:
X_test_sc

array([[ 2.28458741,  1.165441  , -1.31570899, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.54459918, -1.32565851, ..., -0.53100285,
        -0.71708569, -0.54360352],
       [-0.4377158 , -0.78889063,  1.24629372, ...,  1.88322907,
        -0.71708569, -0.54360352],
       ...,
       [-0.4377158 ,  0.92114955,  1.06388576, ..., -0.53100285,
         1.39453348, -0.54360352],
       [-0.4377158 , -1.23675829, -0.67064811, ..., -0.53100285,
         1.39453348, -0.54360352],
       [ 2.28458741,  1.04329527,  0.83504669, ..., -0.53100285,
        -0.71708569, -0.54360352]], shape=(1758, 30))

In [342]:
# Call the DT Classifier
from sklearn.tree import DecisionTreeClassifier

# Initiating the classifier
model_dt = DecisionTreeClassifier()

# Passing the data to classifier
model_dt.fit(X_train_sc, y_train)

y_pred_dt = model_dt.predict(X_test_sc)

In [343]:
y_pred_dt

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(1758,), dtype=object)

In [344]:
# Printing metrics to check how well the model is performing
print("DT Accuracy:", round(accuracy_score(y_test,y_pred_dt)*100, 2), '%')
print("DT Classification Report:")
print(classification_report(y_test,y_pred_dt))

DT Accuracy: 71.16 %
DT Classification Report:
              precision    recall  f1-score   support

          No       0.81      0.79      0.80      1300
         Yes       0.45      0.48      0.47       458

    accuracy                           0.71      1758
   macro avg       0.63      0.64      0.63      1758
weighted avg       0.72      0.71      0.71      1758

In [345]:
'''
RandomOverSampler is a technique used to address class imbalance in datasets by increasing the number of instances in the minority class. It works by randomly duplicating examples from the minority class until the desired balance between classes is achieved. This can help improve the performance of machine learning models, especially when dealing with imbalanced datasets.
'''
from imblearn.over_sampling import RandomOverSampler

# Upsample the minority class using RandomOverSampler
oversampler = RandomOverSampler(sampling_strategy='auto', random_state=42, shrinkage=None)
# Resample the training data to balance the classes
X_train_upsampled, y_train_upsampled = oversampler.fit_resample(X_train_sc, y_train)

# Model Building
model_dt2 = DecisionTreeClassifier()
model_dt2.fit(X_train_upsampled, y_train_upsampled)

# Predict on the test set
y_pred_dt2 = model_dt2.predict(X_test_sc)

In [346]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt2) * 100, 2)
print("DT Upsample Accuracy:", accuracy, '%')
print("DT Upsample Classification Report:")
print(classification_report(y_test,y_pred_dt2))

DT Upsample Accuracy: 72.13 %
DT Upsample Classification Report:
              precision    recall  f1-score   support

          No       0.82      0.80      0.81      1300
         Yes       0.47      0.49      0.48       458

    accuracy                           0.72      1758
   macro avg       0.64      0.65      0.64      1758
weighted avg       0.73      0.72      0.72      1758

In [347]:
y_train_upsampled.head(3) # Displaying the first 3 rows of the upsampled training set

  Churn
0    No
1    No
2   Yes

In [348]:
'''
RandomUnderSampler is a technique used to address class imbalance in datasets by reducing the number of instances in the majority class. It works by randomly selecting a subset of examples from the majority class until the desired balance between classes is achieved. This can help improve the performance of machine learning models, especially when dealing with imbalanced datasets.
'''
from imblearn.under_sampling import RandomUnderSampler

# Downsample the majority class using RandomUnderSampler
downsampler = RandomUnderSampler(sampling_strategy='auto', random_state=42, replacement=False)
# Resample the training data to balance the classes
X_train_downsampled, y_train_downsampled = downsampler.fit_resample(X_train_sc, y_train)

# Model Building
model_dt3 = DecisionTreeClassifier()
model_dt3.fit(X_train_downsampled, y_train_downsampled)

# Predict on the test set
y_pred_dt3 = model_dt3.predict(X_test_sc)

In [349]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt3) * 100, 2)
print("DT Downsample Accuracy:", accuracy, '%')
print("DT Downsample Classification Report:")
print(classification_report(y_test,y_pred_dt3))

DT Downsample Accuracy: 66.84 %
DT Downsample Classification Report:
              precision    recall  f1-score   support

          No       0.85      0.67      0.75      1300
         Yes       0.41      0.65      0.51       458

    accuracy                           0.67      1758
   macro avg       0.63      0.66      0.63      1758
weighted avg       0.73      0.67      0.69      1758

In [350]:
y_train_downsampled.head(3) # Displaying the first 3 rows of the downsampled training set

  Churn
0    No
1    No
2    No

In [351]:
"""
SMOTE (Synthetic Minority Over-sampling Technique) from the Imbalanced-Learn SMOTE Documentation, it creates new, artificial data points for the minority class via K-Nearest Neighbors interpolation instead of blindly copying existing rows. Finds Nearest Neighbors: It targets a minority class instance and looks at its k nearest neighbours (default is 5) within the same minority class. Generates Synthetic Samples: For each minority instance, it randomly selects one of its k nearest neighbours and generates a new synthetic instance along the line segment connecting the two instances. This process is repeated until the desired balance between classes is achieved.
"""
from imblearn.over_sampling import SMOTE
# Create a SMOTE object
smote = SMOTE(random_state=42, sampling_strategy='auto', k_neighbors=5)

# Resample the data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_sc, y_train)

# Model Building
model_dt4 = DecisionTreeClassifier()
model_dt4.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt4 = model_dt4.predict(X_test_sc)

In [352]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt4) * 100, 2)
print("DT SMOTE Accuracy:", accuracy, '%')
print("DT SMOTE Classification Report:")
print(classification_report(y_test, y_pred_dt4))

DT SMOTE Accuracy: 72.01 %
DT SMOTE Classification Report:
              precision    recall  f1-score   support

          No       0.82      0.79      0.81      1300
         Yes       0.47      0.52      0.49       458

    accuracy                           0.72      1758
   macro avg       0.65      0.66      0.65      1758
weighted avg       0.73      0.72      0.72      1758

In [353]:
"""
SMOTEENN is a hybrid technique from the imblearn library that combines SMOTE (oversampling) with Edited Nearest Neighbors (ENN) (undersampling).
While standard SMOTE is great at creating synthetic minority points, it often creates them too close to—or directly inside—the majority class boundary. This creates a noisy, blurry decision boundary. SMOTEENN solves this by cleaning up the noise after oversampling.
1. Oversample (SMOTE): It creates synthetic data points for your minority class to balance the dataset.
2. Clean & Undersample (ENN): It examines every data point using a K-Nearest Neighbors approach. If a data point's neighbors mostly belong to the opposite class, that data point is removed. This deletes noisy majority points and poorly placed synthetic minority points.
The result is a clean, distinct "no man's land" between your two classes, making it much easier for your machine learning model to find the correct decision boundary.
"""
from imblearn.combine import SMOTEENN

# Create a SMOTEENN object
smote_enn = SMOTEENN(random_state=42, sampling_strategy='auto', smote=None, enn=None, n_jobs=1)

# Resample the data
X_train_resampled, y_train_resampled = smote_enn.fit_resample(X_train_sc, y_train)

# Model Building
model_dt5 = DecisionTreeClassifier()
model_dt5.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt5 = model_dt5.predict(X_test_sc)

#

In [354]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt5) * 100, 2)
print("DT SMOTEENN Accuracy:", accuracy, '%')
print("DT SMOTEENN Classification Report:")
print(classification_report(y_test, y_pred_dt5))

DT SMOTEENN Accuracy: 70.99 %
DT SMOTEENN Classification Report:
              precision    recall  f1-score   support

          No       0.89      0.70      0.78      1300
         Yes       0.46      0.75      0.57       458

    accuracy                           0.71      1758
   macro avg       0.68      0.72      0.68      1758
weighted avg       0.78      0.71      0.73      1758

In [356]:
"""
ADASYN (Adaptive Synthetic Sampling) is an advanced oversampling technique from the imblearn library. It builds upon standard SMOTE by shifting its focus to the most difficult-to-learn regions of your dataset.
While SMOTE generates synthetic data points uniformly across all minority examples, ADASYN adaptively creates more synthetic data in areas where the minority class is heavily outnumbered by the majority class.
ADASYN determines exactly where to generate data by looking at the density distribution:
1. Measures Local Difficulty: For every minority data point, it looks at its K-Nearest Neighbors. It calculates the ratio of majority class examples surrounding that point.
2. Assigns Weights: A minority point surrounded by many majority points is flagged as "hard to learn" and given a high weight. A minority point surrounded by other minority points is flagged as "easy to learn" and given a low weight.
3. Generates Adaptively: It generates significantly more synthetic data points around the high-weight (difficult) examples and fewer around the easy ones.
This forces the machine learning model to focus on the challenging boundary regions where it is most likely to make errors.
Critical Traps & When to Avoid ADASYN:
While ADASYN is highly effective, it has one major drawback: outliers.
If your minority class contains extreme outliers or noise (e.g., an incorrectly labeled data point deep inside the majority class territory), ADASYN will see it as the "hardest" point to learn. It will mistakenly generate a massive cluster of synthetic data right around that noisy outlier, creating false patterns.
"""
from imblearn.over_sampling import ADASYN

# Create an ADASYN object
adasyn = ADASYN(random_state=42)

# Resample the data
X_train_resampled, y_train_resampled = adasyn.fit_resample(X_train_sc, y_train)

# Model Building
model_dt6 = DecisionTreeClassifier()
model_dt6.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt6 = model_dt6.predict(X_test_sc)

In [357]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt6) * 100, 2)
print("DT ADASYN Accuracy:", accuracy, '%')
print("DT ADASYN Classification Report:")
print(classification_report(y_test, y_pred_dt6))

DT ADASYN Accuracy: 71.39 %
DT ADASYN Classification Report:
              precision    recall  f1-score   support

          No       0.83      0.77      0.80      1300
         Yes       0.46      0.56      0.50       458

    accuracy                           0.71      1758
   macro avg       0.65      0.66      0.65      1758
weighted avg       0.73      0.71      0.72      1758

In [358]:
"""
AllKNN is an under-sampling technique from the imblearn.under_sampling module. It is a smart data-cleaning tool that focuses entirely on removing noisy, ambiguous majority class data points right along the decision boundary.
Unlike standard RandomUnderSampler (which blindly deletes data at random), AllKNN uses spatial mathematics to eliminate data points that blur the line between your classes.
How AllKNN Works Behind the Scenes:
AllKNN is a strategic expansion of Edited Nearest Neighbors (ENN). It cleans the majority class in a series of loop iterations:
1. Iteration 1 (k=1): It checks the 1 nearest neighbor of every majority class data point. If that neighbor belongs to the minority class (meaning the majority point is isolated or floating in enemy territory), that majority point is deleted.
2. Iteration 2 (k=2): It expands the neighborhood size by 1. It checks the 2 nearest neighbors of the surviving points and removes those that mismatch.
3. Subsequent Iterations ((k=3, ..., n)): It continues increasing the value of k by 1 at each round.
The process stops when it reaches your maximum specified n_neighbors (the default is 3) or if the majority class shrinks so much that it accidentally becomes the minority class
"""
from imblearn.under_sampling import AllKNN

# Create an AllKNN object
allknn = AllKNN(sampling_strategy='auto', n_neighbors=3, n_jobs=1)

# Resample the data
X_train_resampled, y_train_resampled = allknn.fit_resample(X_train_sc, y_train)

# Model Building
model_dt7 = DecisionTreeClassifier()
model_dt7.fit(X_train_resampled, y_train_resampled)

# Predict on the test set
y_pred_dt7 = model_dt7.predict(X_test_sc)

In [359]:
# Calculate accuracy and Print classification report
accuracy = round(accuracy_score(y_test, y_pred_dt7) * 100, 2)
print("DT ALLkNN Accuracy:", accuracy, '%')
print("DT ALLkNN Classification Report:")
print(classification_report(y_test, y_pred_dt7))

DT ALLkNN Accuracy: 67.18 %
DT ALLkNN Classification Report:
              precision    recall  f1-score   support

          No       0.92      0.61      0.73      1300
         Yes       0.43      0.85      0.57       458

    accuracy                           0.67      1758
   macro avg       0.68      0.73      0.65      1758
weighted avg       0.79      0.67      0.69      1758

In [360]:
# Assume 'df' is our dataframe containing the dataset loaded from a CSV file or any other source. The following code demonstrates how to preprocess the data, handle class imbalance, and train a decision tree classifier.
# Separate features and target variable just like before
from imblearn.under_sampling import TomekLinks
from sklearn.tree import DecisionTreeClassifier
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

In [361]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',         'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',  'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [362]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

In [363]:
# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [364]:
# Use AllKNN for undersampling
allknn = AllKNN(sampling_strategy='auto')
X_train_resampled, y_train_resampled = allknn.fit_resample(X_train, y_train)

In [365]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

In [366]:
# Create a decision tree classifier with appropriate parameters
print("Training decision tree...")
dtc = DecisionTreeClassifier(random_state=42, max_depth=5)  # Adjust parameters as needed
dtc.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc.predict(X_test_scaled)

Training decision tree...

In [367]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")

Accuracy of decision tree: 73.54948805460751 %

In [368]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.91      0.71      0.80      1291
         Yes       0.50      0.81      0.62       467

    accuracy                           0.74      1758
   macro avg       0.71      0.76      0.71      1758
weighted avg       0.80      0.74      0.75      1758

In [369]:
# Assume 'df' is your dataframe containing the dataset
# Separate features and target variable
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

In [370]:
# Convert categorical features to numericals --> Feature Encoding --> Dummy Encoding
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True)

In [371]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [372]:
# Use TomekLinks for undersampling
tomek_links = TomekLinks(sampling_strategy='majority')  # not majority gives better results
X_train_resampled, y_train_resampled = tomek_links.fit_resample(X_train, y_train)

In [373]:
# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

In [374]:
# Create a decision tree classifier
dtc = DecisionTreeClassifier(random_state=42)

In [375]:
# Define the parameter grid for fine-tuning
param_grid = {
    'max_depth': [3, 5, 7, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [376]:
# Use GridSearchCV for fine-tuning
grid_search = GridSearchCV(dtc, param_grid, cv=5, scoring='accuracy', n_jobs=1)
grid_search.fit(X_train_scaled, y_train_resampled)

# Get the best parameters from the grid search
best_params = grid_search.best_params_

In [378]:
# Print the best parameters
print("Best Parameters:", best_params)

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}

In [379]:
# Create a decision tree classifier with the best parameters
dtc_best = DecisionTreeClassifier(random_state=42, **best_params)
dtc_best.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc_best.predict(X_test_scaled)

In [380]:
# Evaluate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")

Accuracy of decision tree: 78.32764505119454 %

In [381]:
# Print classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.86      0.85      0.85      1291
         Yes       0.59      0.61      0.60       467

    accuracy                           0.78      1758
   macro avg       0.72      0.73      0.72      1758
weighted avg       0.79      0.78      0.78      1758

In [382]:
"""
SMOTETOMEK is a powerful hybrid resampling technique from the imblearn.combine module. Just like SMOTEENN, it aims to solve the problem of blurry class boundaries by combining oversampling and undersampling into a unified, two-step workflow.
Instead of using ENN to clean up data points, it specifically hunts down and eliminates Tomek Links.
What is a Tomek Link?
A Tomek Link occurs when two data points from opposite classes are each other’s immediate nearest neighbours.
Imagine a "Yes Churn" data point and a "No Churn" data point sitting incredibly close together in your feature space, isolated from their own respective groups. This pairing creates a high level of ambiguity for your machine learning model. By identifying these links and deleting the majority class instance (or both), you widen the gap between your classes.
How SMOTETOMEK Works:
1. Oversample (SMOTE): It first uses standard SMOTE to generate synthetic minority data points, bringing the classes to an equal balance.
2. Find and Destroy (Tomek Links): It scans the newly expanded dataset to identify all Tomek Links. It then removes the majority class data point from every pair.
This leaves you with a much cleaner, more distinct separation zone between your target categories.
"""
from imblearn.combine import SMOTETomek

In [383]:
# Assume 'df' is your dataframe containing the dataset

# Separate features and target variable
X = df.drop(['customerID', 'Churn'], axis=1)  # Replace with your target column name
y = df["Churn"]

X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'], drop_first=True, dtype='int')

In [384]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [385]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: str

In [386]:
# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)  # Stratified split for imbalanced data

# Check for class imbalance in training data
print("Class imbalance in training data:")
print(y_train.value_counts())

Class imbalance in training data:
Churn
No     3872
Yes    1402
Name: count, dtype: int64

In [387]:
# Use SMOTETomek for both over-sampling and under-sampling
smote_tomek = SMOTETomek(sampling_strategy=0.5, random_state=42)
X_train_resampled, y_train_resampled = smote_tomek.fit_resample(X_train, y_train)

# Standardize the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_resampled)
X_test_scaled = scaler.transform(X_test)

# Create a decision tree classifier with appropriate parameters
print("Training decision tree...")
dtc = DecisionTreeClassifier(random_state=42, max_depth=5)  # Adjust parameters as needed
dtc.fit(X_train_scaled, y_train_resampled)

# Make predictions on the test set
y_pred = dtc.predict(X_test_scaled)

Training decision tree...

In [388]:
# Evaluate accuracy and Print classification report
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy of decision tree:", accuracy * 100, "%")
print(classification_report(y_test, y_pred))

Accuracy of decision tree: 77.7019340159272 %
              precision    recall  f1-score   support

          No       0.84      0.86      0.85      1291
         Yes       0.58      0.56      0.57       467

    accuracy                           0.78      1758
   macro avg       0.71      0.71      0.71      1758
weighted avg       0.77      0.78      0.78      1758